---
collections:
  # Install a collection from Ansible Galaxy.
  - name: servicenow.servicenow
    source: https://galaxy.ansible.com

  - name: cisco.ios
    source: https://cloud.redhat.com/api/automation-hub/
