---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow
  
  tasks:
  - name: Create an incident
    snow_record:
      username: "{{ lookup('env','SNOW_USER') }}"
      password: "{{ lookup('env','SNOW_PASSWORD') }}"
      instance: "{{ lookup('env','SNOW_INSTANCE') }}"
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident

  - debug: 
      var: new_incident.record.number