---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow
  
  tasks:
  - name: Create an incident
    snow_record:
      username: "{{ lookup('env','SN_USERNAME')  | default(snow_user, true)}}"
      password: "{{ lookup('env','SN_PASSWORD') | default(snow_password, true) }}"
      instance: "{{ lookup('env','SNOW_INSTANCE')  | default(snow_instance, true) }}"
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident

  - set_stats:
      data:
        snow_number: "{{ new_incident.record.number }}"

  - debug: 
      var: new_incident.record.number