---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.servicenow

  tasks:
    - name: Create an incident
      snow_record:
        state: present
        data:
          short_description: "This is a test incident opened by Ansible"
          severity: 3
          priority: 2
      register: new_incident

    - name: Save incident record number
      set_stats:
        data:
          snow_number: "{{ new_incident.record.number }}"

    - debug:
        var: new_incident.record.number
