---
- name: Parse IOS 'show version' with Genie parser
  hosts: "{{ my_devices }}"
  gather_facts: "{{ my_facts }}"
  connection: network_cli
  roles:
    - clay584.parse_genie

  tasks:
  - name: Parse 'show version'
    set_stats:
      data:
        # show_version comes from a previous Job Template in a Workflow
        pyats_version: "{{ show_version | parse_genie(command='show version', os='ios') }}"

  - name: Show parsed command
    debug:
      var: pyats_version