---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow

  tasks:
  - name: Modify an Incident
    snow_record:
      username: "{{ lookup('env','SN_USERNAME')  | default(snow_user, true) }}"
      password: "{{ lookup('env','SN_PASSWORD') | default(snow_password, true) }}"
      instance: "{{ lookup('env','SNOW_INSTANCE')  | default(snow_instance, true) }}"
      state: present
      # table: change_request
      table: incident
      number: "{{ lookup('env','SNOW_NUMBER') | default(snow_number, true) }}"
      data:
        u_device_up_time: "{{ pyats_version.version.uptime | default('N/A', true)  }}"
        u_ios_version: "{{ pyats_version.version.version | default('N/A', true)  }}"
        u_hostname: "{{ pyats_version.version.hostname | default('N/A', true)  }}"
        u_platform: "{{ pyats_version.version.platform | default('N/A', true)  }}"
        u_device_type: "{{ pyats_version.version.rtr_type | default('N/A', true)  }}"
        u_serial_number: "{{ pyats_version.version.chassis_sn | default('N/A', true)  }}"
        u_last_reload_reason: "{{ pyats_version.version.last_reload_reason | default('N/A', true)  }}"
    register: incident

  - debug:
      var: incident.record.state